# Minimal Codecov configuration for Polydros
# See https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "0...100"

status:
  project:
    default:
      target: 100

flags:
  unit: {}
